src/Entity/Property.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use App\Entity\Traits\Timestampable;
use App\Repository\PropertyRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @ORM\Table(name="properties")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity("title")
 */
class Property
{
    const TYPE = [
        0 => 'Villa',
        1 => 'Studio',
        2 => 'Duplex'
    ];

    const STATUS = [
        0 => 'A louer',
        1 => 'A vendre'
    ];

    use Timestampable;
    
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Donnez un titre a votre bien")
     * @Assert\Length(min=4)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Une brieve description du bien")
     * @Assert\Length(min=16)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="La surperficie est obligatoire")
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Le nombre de pieces est obligatoire")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Le nombre de chambres est obligatoire")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Dites dans quelle ville se trouve le bien")
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="L'adresse precise du bien")
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $postalCode;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     * @Assert\NotBlank(message="Mentionnez si c'est vendu ou pas / louer ou libre")
     */
    private $sold = false;

    /**
     * @ORM\Column(type="integer")
     */
    private $parking;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Obligatoire")
     */
    private $status;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Mentionner le type de bien")
     */
    private $type;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Mettez un prix de location ou d'achat")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Dites dans quel pays se trouve le bien")
     */
    private $country;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    public function setPostalCode(?string $postalCode): self
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getParking(): ?int
    {
        return $this->parking;
    }

    public function setParking(int $parking): self
    {
        $this->parking = $parking;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getStatusType(): string
    {
        return self::STATUS[$this->status];
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getTypeType(): string
    {
        return self::TYPE[$this->type];
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\PropertyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(PropertyRepository $repository): Response
    {
        $properties = $repository->findLatesst();

        return $this->render('home/index.html.twig', [
            'properties' => $properties,
            'current_menu' => 'home',
        ]);
    }
}

templates/Home/partials/_intro_section.html.twig
<div class="intro intro-carousel swiper position-relative">
    <div class="swiper-wrapper">
        {% for property in properties %}
            <div class="swiper-slide carousel-item-a intro-item bg-image" style="background-image: url(assets/img/slide-1.jpg)">
                <div class="overlay overlay-a"></div>
                    <div class="intro-content display-table">
                    <div class="table-cell">
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-8">
                                    <div class="intro-body">
                                        <p class="intro-title-top">{{property.address}}, {{property.city}}, {{property.country}}
                                        <br> {{property.postalCode}}
                                        </p>
                                        <h1 class="intro-title mb-4 ">
                                            <span class="color-b">{{property.typeType}} </span>
                                            <br> {{property.title}}
                                        </h1>
                                        <p class="intro-subtitle intro-price">
                                            <a href="#"><span class="price-a">{{property.statusType}} | {{property.formattedPrice}} fcfa</span></a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="swiper-pagination"></div>
</div>

templates/Home/partials/_latest_properties_section.html.twig
<section class="section-property section-t8">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-wrap d-flex justify-content-between">
                    <div class="title-box">
                        <h2 class="title-a">Dernières propriétés</h2>
                    </div>
                    <div class="title-link">
                        <a href="{{ path('app_property') }}">Toutes les propriétés
                            <span class="bi bi-chevron-right"></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div id="property-carousel" class="swiper">
            <div class="swiper-wrapper">
                {% for property in properties %}
                    <div class="carousel-item-b swiper-slide">
                        <div class="card-box-a card-shadow">
                            <div class="img-box-a">
                                <img src="assets/img/property-6.jpg" alt="" class="img-a img-fluid">
                            </div>
                            <div class="card-overlay">
                                <div class="card-overlay-a-content">
                                    <div class="card-header-a">
                                        <h2 class="card-title-a">
                                            <a href="{{ path('app_property_show', {id: property.id, slug: property.slug}) }}">
                                                {{property.typeType}}
                                                <br /> {{property.title}}
                                            </a>
                                        </h2>
                                    </div>
                                    <div class="card-body-a">
                                        <div class="price-box d-flex">
                                            <span class="price-a">{{property.statusType}} | {{property.formattedPrice}} fcfa</span>
                                        </div>
                                        <a href="{{ path('app_property_show', {id: property.id, slug: property.slug}) }}" class="link-a">Cliquez ici pour voir
                                            <span class="bi bi-chevron-right"></span>
                                        </a>
                                    </div>
                                    <div class="card-footer-a">
                                        <ul class="card-info d-flex justify-content-around">
                                            <li>
                                                <h4 class="card-info-title">Superficie</h4>
                                                <span>{{property.surface}}m
                                                    <sup>2</sup>
                                                </span>
                                            </li>
                                            <li>
                                                <h4 class="card-info-title">Pieces</h4>
                                                <span>{{property.rooms}}</span>
                                            </li>
                                            <li>
                                                <h4 class="card-info-title">Chambres</h4>
                                                <span>{{property.bedrooms}}</span>
                                            </li>
                                            <li>
                                                <h4 class="card-info-title">Parking</h4>
                                                <span>{{property.parking}}</span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="propery-carousel-pagination carousel-pagination"></div>
    </div>
</section>

templates/Home/partials/_services_section.html.twig
<section class="section-services section-t8">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-wrap d-flex justify-content-between">
                    <div class="title-box">
                        <h2 class="title-a">Nos services</h2>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="card-box-c foo">
                    <div class="card-header-c d-flex">
                        <div class="card-box-ico">
                            <span class="bi bi-cart"></span>
                        </div>
                        <div class="card-title-c align-self-center">
                            <h2 class="title-c">Vente</h2>
                        </div>
                    </div>
                    <div class="card-body-c">
                        <p class="content-c">
                            Sed porttitor lectus nibh. Cras ultricies ligula sed magna dictum porta. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi.
                        </p>
                    </div>
                    <div class="card-footer-c">
                        <a href="#" class="link-c link-icon">Lire la suite
                            <span class="bi bi-chevron-right"></span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card-box-c foo">
                    <div class="card-header-c d-flex">
                        <div class="card-box-ico">
                            <span class="bi bi-calendar4-week"></span>
                        </div>
                        <div class="card-title-c align-self-center">
                            <h2 class="title-c">Location</h2>
                        </div>
                    </div>
                    <div class="card-body-c">
                        <p class="content-c">
                            Nulla porttitor accumsan tincidunt. Curabitur aliquet quam id dui posuere blandit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a.
                        </p>
                    </div>
                    <div class="card-footer-c">
                        <a href="#" class="link-c link-icon">Lire la suite
                            <span class="bi bi-calendar4-week"></span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card-box-c foo">
                    <div class="card-header-c d-flex">
                        <div class="card-box-ico">
                            <span class="bi bi-card-checklist"></span>
                        </div>
                        <div class="card-title-c align-self-center">
                            <h2 class="title-c">Conseil</h2>
                        </div>
                    </div>
                    <div class="card-body-c">
                        <p class="content-c">
                            Sed porttitor lectus nibh. Cras ultricies ligula sed magna dictum porta. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi.
                        </p>
                    </div>
                    <div class="card-footer-c">
                        <a href="#" class="link-c link-icon">Lire la suite
                            <span class="bi bi-chevron-right"></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>